# Generated by Django 4.1.1 on 2022-09-15 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("drawing", models.URLField(default="", max_length=1000)),
                ("drawing_x", models.IntegerField(default=0)),
                ("drawing_y", models.IntegerField(default=0)),
                ("drawing_station1_x", models.IntegerField(default=0)),
                ("drawing_station1_y", models.IntegerField(default=0)),
                ("drawing_station2_x", models.IntegerField(default=0)),
                ("drawing_station2_y", models.IntegerField(default=0)),
                ("drawing_station3_x", models.IntegerField(default=0)),
                ("drawing_station3_y", models.IntegerField(default=0)),
                ("drawing_station4_x", models.IntegerField(default=0)),
                ("drawing_station4_y", models.IntegerField(default=0)),
                ("real_x", models.IntegerField(default=0)),
                ("real_y", models.IntegerField(default=0)),
                ("real_station1_x", models.IntegerField(default=0)),
                ("real_station1_y", models.IntegerField(default=0)),
                ("real_station2_x", models.IntegerField(default=0)),
                ("real_station2_y", models.IntegerField(default=0)),
                ("real_station3_x", models.IntegerField(default=0)),
                ("real_station3_y", models.IntegerField(default=0)),
                ("real_station4_x", models.IntegerField(default=0)),
                ("real_station4_y", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("subjects", models.CharField(default="", max_length=100)),
                (
                    "hospital",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.hospital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("gender", models.BooleanField(default=True)),
                ("age", models.IntegerField(default=0)),
                ("blood_type", models.IntegerField(default=0)),
                ("blood_rh", models.BooleanField(default=True)),
                ("disease", models.TextField(default="")),
                ("extra", models.TextField(default="")),
                ("image", models.IntegerField(default=0)),
                ("real_distance1", models.FloatField(default=0.0)),
                ("real_distance2", models.FloatField(default=0.0)),
                ("real_distance3", models.FloatField(default=0.0)),
                ("real_distance4", models.FloatField(default=0.0)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
